# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        # You may use a newer version of https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Generate your content
        run: npm ci && npm run build

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional.
          #
          # Default value "." means the root directory of your project will be published.
          #
          # You can use whatever directory your project uses,
          # for example "wwwroot" (without leading "./").
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically
          # by your static website builder.
          source-directory: public

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will REMOVE this branch and replace it with new content.
          # (If you want to keep your old "gh-pages" branch,
          # you should define a different target branch for this GPO action to work with.)
          target-branch: gh-pages
